### ISSUE TITLE
Aqara Temp/humid sensor is unresponsive in Home App

### ISSUE THREAD

**Issue by tr1ng0** [madchicken/homebridge-zigbee-nt#84] opened 2021-01-19 14:09 UTC
Even with official 2.0.0 release it is still not working with the Home App.

Zigbee ID: "lumi.weather"
Model WSDCGQ11LM

![IMG_BB6E9C0E23C1-1](https://user-images.githubusercontent.com/39862487/105045423-2f347e00-5a68-11eb-8277-7c5d34922c54.jpeg)

EDIT: it does work with homebridge ui

**Comment by madchicken** [comment] 2021-01-19 14:39
I need help here: can you provide some log? I don't understand what is happening

**Comment by madchicken** [comment] 2021-01-21 15:50
Closing as duplicate of #69

**Closed by madchicken** 2021-01-21 15:50 UTC
