### ISSUE TITLE
Errors in RC2 

### ISSUE THREAD

**Issue by manuchis** [madchicken/homebridge-zigbee-nt#12] opened 2020-07-18 10:42 UTC
After updating to RC2 I cannot run the plugin (I built it in local, RC1 works well):

```
[7/18/2020, 12:39:17] ====================
[7/18/2020, 12:39:17] ERROR LOADING PLUGIN homebridge-zigbee-nt:
[7/18/2020, 12:39:17] TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>:null:null)
    at extendStatics (/home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:8:16)
    at __extends (/home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:11:9)
    at /home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:23:5
    at Object.<anonymous> (/home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/gen/HomeKit.js:38:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/gen/index.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/Characteristic.js:30:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/manuchis/homebridge-zigbee-nt/node_modules/hap-nodejs/dist/lib/gen/HomeKit-Bridge.js:16:24)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/manuchis/homebridge-zigbee-nt/dist/accessories/tuya/tuya-onoff-double-switch.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/manuchis/homebridge-zigbee-nt/dist/index.js:14:36)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (/usr/local/lib/node_modules/homebridge-broadlink-rm-pro/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:124:31)
    at /usr/local/lib/node_modules/homebridge/lib/pluginManager.js:63:24
    at Map.forEach (<anonymous>:null:null)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:61:22)
    at Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:71:28)
    at cli (/usr/local/lib/node_modules/homebridge/lib/cli.js:88:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by madchicken** [comment] 2020-07-21 15:53
Thanks for reporting, could you try with the RC3 branch?

**Comment by madchicken** [comment] 2020-07-22 16:30
I am pretty sure the problem is related to a wrong dependency and I see it resolved in RC3 branch. I will release it soon

**Closed** 2020-07-23 19:37 UTC
